flowY += COMPONENT_SPACING;
const badgeText = penpot.createText("NOUVEAUTÉ");
badgeText.fontSize = 13;
badgeText.fontWeight = "bold";
badgeText.fills = [{ fillColor: TEXT_COLOR, fillOpacity: 0.95 }];
badgeText.resize(200, 10);
const badgeWidth = badgeText.width + 36;
const badge = penpot.createRectangle();
badge.name = "Badge";
badge.x = columnX;
badge.y = flowY;
badge.resize(badgeWidth, 36);
badge.borderRadius = 999;
badge.fills = [{ fillColor: 'rgba(255,255,255,0.18)', fillOpacity: 1 }];
created.push(badge);
badgeText.x = badge.x + (badgeWidth - badgeText.width) / 2;
badgeText.y = badge.y + (36 - badgeText.height) / 2;
created.push(badgeText);
flowY += badge.height + 30;